### ISSUE TITLE
Mocking framework

### ISSUE THREAD

**Issue by oleksiyp** [ryuta46/nem-kotlin#4]
Hi,

hope find you well with this cold call.

I am an author of [mocking framework for Kotlin](http://mockk.io)

I see you are using mockito-kotlin.

I just want you to be aware that there is solution that fully supports Kotlin and ask to try it in your new/current projects.

I can help you if you answer to this issue.

Thanks and please star [it](https://github.com/oleksiyp/mockk)

**Comment by ryuta46** [comment]
Thank you for letting me know about your product.

I'm very interested in the mocking framework.

I'll try it when I upgrade "nem-kotlin".

Thanks.
